In [1]:
import numpy as np
import pandas as pd
import os
import sys

curr_dir = os.path.dirname(os.path.abspath('__file__'))
parent_dir = os.path.dirname(curr_dir)
sys.path.append(parent_dir+'/src')

from utils import *
from features import *

2023-08-09 08:50:22,286 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.

### 1. 类别特征交叉组合衍生函数

In [2]:
# 显示所有列
pd.set_option('display.max_columns', None)
# 设置一行的宽度
pd.set_option('display.width', 5000)
# 读取数据
t = pd.read_csv('../data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv')
# 标注 离散字段和连续字段
# 离散字段
category_cols = ['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService',
                 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
                 'Contract', 'PaperlessBilling', 'PaymentMethod']
# 连续字段
numeric_cols = ['tenure', 'MonthlyCharges', 'TotalCharges']
# 标签
target = 'Churn'
# ID列
ID_col = 'customerID'
# 连续字段转化
t['TotalCharges'] = t['TotalCharges'].apply(lambda x: x if x != ' ' else np.nan).astype(float)
t['MonthlyCharges'] = t['MonthlyCharges'].astype(float)
# 缺失值填补
t['TotalCharges'] = t['TotalCharges'].fillna(0)
# 标签值手动转化
t['Churn'].replace(to_replace='Yes', value=1, inplace=True)
t['Churn'].replace(to_replace='No', value=0, inplace=True)
features = t.drop(columns=[ID_col, target]).copy()
labels = t['Churn'].copy()
print(features.head(5))
print('-' * 10)
print(labels)

   gender  SeniorCitizen Partner Dependents  tenure PhoneService     MultipleLines InternetService OnlineSecurity OnlineBackup DeviceProtection TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling              PaymentMethod  MonthlyCharges  TotalCharges
0  Female              0     Yes         No       1           No  No phone service             DSL             No          Yes               No          No          No              No  Month-to-month              Yes           Electronic check           29.85         29.85
1    Male              0      No         No      34          Yes                No             DSL            Yes           No              Yes          No          No              No        One year               No               Mailed check           56.95       1889.50
2    Male              0      No         No       2          Yes                No             DSL            Yes          Yes               No          No          No              No  Month-to-month              Yes               Mailed check           53.85        108.15
3    Male              0      No         No      45           No  No phone service             DSL            Yes           No              Yes         Yes          No              No        One year               No  Bank transfer (automatic)           42.30       1840.75
4  Female              0      No         No       2          Yes                No     Fiber optic             No           No               No          No          No              No  Month-to-month              Yes           Electronic check           70.70        151.65
----------
0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7043, dtype: int64

In [3]:
col_names = ['SeniorCitizen', 'Partner', 'Dependents']
get_binary_cross_comb_feat(features, col_names, encode='label')

      gender  SeniorCitizen Partner Dependents  tenure PhoneService     MultipleLines InternetService OnlineSecurity OnlineBackup DeviceProtection TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling              PaymentMethod  MonthlyCharges  TotalCharges  Partner_Dependents  SeniorCitizen_Dependents  SeniorCitizen_Partner
0     Female              0     Yes         No       1           No  No phone service             DSL             No          Yes               No          No          No              No  Month-to-month              Yes           Electronic check           29.85         29.85                   0                         0                      0
1       Male              0      No         No      34          Yes                No             DSL            Yes           No              Yes          No          No              No        One year               No               Mailed check           56.95       1889.50                   1                         0                      1
2       Male              0      No         No       2          Yes                No             DSL            Yes          Yes               No          No          No              No  Month-to-month              Yes               Mailed check           53.85        108.15                   1                         0                      1
3       Male              0      No         No      45           No  No phone service             DSL            Yes           No              Yes         Yes          No              No        One year               No  Bank transfer (automatic)           42.30       1840.75                   1                         0                      1
4     Female              0      No         No       2          Yes                No     Fiber optic             No           No               No          No          No              No  Month-to-month              Yes           Electronic check           70.70        151.65                   1                         0                      1
...      ...            ...     ...        ...     ...          ...               ...             ...            ...          ...              ...         ...         ...             ...             ...              ...                        ...             ...           ...                 ...                       ...                    ...
7038    Male              0     Yes        Yes      24          Yes               Yes             DSL            Yes           No              Yes         Yes         Yes             Yes        One year              Yes               Mailed check           84.80       1990.50                   3                         1                      0
7039  Female              0     Yes        Yes      72          Yes               Yes     Fiber optic             No          Yes              Yes          No         Yes             Yes        One year              Yes    Credit card (automatic)          103.20       7362.90                   3                         1                      0
7040  Female              0     Yes        Yes      11           No  No phone service             DSL            Yes           No               No          No          No              No  Month-to-month              Yes           Electronic check           29.60        346.45                   3                         1                      0
7041    Male              1     Yes         No       4          Yes               Yes     Fiber optic             No           No               No          No          No              No  Month-to-month              Yes               Mailed check           74.40        306.60                   0                         2                      3
7042    Male              0      No         No      66          Yes                No     Fiber optic            Yes           No              Yes         Yes         Yes             Yes        Two year              Yes  Bank transfer (automatic)          105.65       6844.50                   1                         0                      1

[7043 rows x 22 columns]

In [4]:
col_names = ['SeniorCitizen', 'Partner', 'Dependents']
get_multi_cross_comb_feat(features, col_names, encode='onehot')

      gender  SeniorCitizen Partner Dependents  tenure PhoneService     MultipleLines InternetService OnlineSecurity OnlineBackup DeviceProtection TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling              PaymentMethod  MonthlyCharges  TotalCharges  SeniorCitizen_Partner_Dependents_0_No_No  SeniorCitizen_Partner_Dependents_0_No_Yes  SeniorCitizen_Partner_Dependents_0_Yes_No  SeniorCitizen_Partner_Dependents_0_Yes_Yes  SeniorCitizen_Partner_Dependents_1_No_No  SeniorCitizen_Partner_Dependents_1_No_Yes  SeniorCitizen_Partner_Dependents_1_Yes_No  SeniorCitizen_Partner_Dependents_1_Yes_Yes
0     Female              0     Yes         No       1           No  No phone service             DSL             No          Yes               No          No          No              No  Month-to-month              Yes           Electronic check           29.85         29.85                                         0                                          0                                          1                                           0                                         0                                          0                                          0                                           0
1       Male              0      No         No      34          Yes                No             DSL            Yes           No              Yes          No          No              No        One year               No               Mailed check           56.95       1889.50                                         1                                          0                                          0                                           0                                         0                                          0                                          0                                           0
2       Male              0      No         No       2          Yes                No             DSL            Yes          Yes               No          No          No              No  Month-to-month              Yes               Mailed check           53.85        108.15                                         1                                          0                                          0                                           0                                         0                                          0                                          0                                           0
3       Male              0      No         No      45           No  No phone service             DSL            Yes           No              Yes         Yes          No              No        One year               No  Bank transfer (automatic)           42.30       1840.75                                         1                                          0                                          0                                           0                                         0                                          0                                          0                                           0
4     Female              0      No         No       2          Yes                No     Fiber optic             No           No               No          No          No              No  Month-to-month              Yes           Electronic check           70.70        151.65                                         1                                          0                                          0                                           0                                         0                                          0                                          0                                           0
...      ...            ...     ...        ...     ...          ...               ...             ...            ...          ...              ...         ...         ...             ...             ...              ...                        ...             ...           ...                                       ...                                        ...                                        ...                                         ...                                       ...                                        ...                                        ...                                         ...
7038    Male              0     Yes        Yes      24          Yes               Yes             DSL            Yes           No              Yes         Yes         Yes             Yes        One year              Yes               Mailed check           84.80       1990.50                                         0                                          0                                          0                                           1                                         0                                          0                                          0                                           0
7039  Female              0     Yes        Yes      72          Yes               Yes     Fiber optic             No          Yes              Yes          No         Yes             Yes        One year              Yes    Credit card (automatic)          103.20       7362.90                                         0                                          0                                          0                                           1                                         0                                          0                                          0                                           0
7040  Female              0     Yes        Yes      11           No  No phone service             DSL            Yes           No               No          No          No              No  Month-to-month              Yes           Electronic check           29.60        346.45                                         0                                          0                                          0                                           1                                         0                                          0                                          0                                           0
7041    Male              1     Yes         No       4          Yes               Yes     Fiber optic             No           No               No          No          No              No  Month-to-month              Yes               Mailed check           74.40        306.60                                         0                                          0                                          0                                           0                                         0                                          0                                          1                                           0
7042    Male              0      No         No      66          Yes                No     Fiber optic            Yes           No              Yes         Yes         Yes             Yes        Two year              Yes  Bank transfer (automatic)          105.65       6844.50                                         1                                          0                                          0                                           0                                         0                                          0                                          0                                           0

[7043 rows x 27 columns]

### 2. 时序特征衍生函数

In [5]:
import pandas as pd

# 显示所有列
pd.set_option('display.max_columns', None)
# 设置一行的宽度
pd.set_option('display.width', 5000)

t = pd.DataFrame()
t['time'] = ['2022-01-03 02:31:52',
             '2022-07-01 14:22:01',
             '2022-08-22 08:02:31',
             '2022-04-30 11:41:31',
             '2022-05-02 22:01:27']

timeStamp = {'p1': '2022-03-25 23:21:52', 'p2': '2022-02-15 08:51:02'}

In [6]:
get_time_series_feat(time_series=t['time'], time_series_format='%Y-%m-%d %H:%M:%S', time_dict=timeStamp, 
                     time_dict_format='%Y-%m-%d %H:%M:%S', is_exact_hms=True)

   time_year  time_quarter  time_month  time_day  time_hour  time_minute  time_second  time_weekofyear  time_dayofweek  time_weekend  time_hour_sec  time_day_or_night  time_diff_days_p1  time_diff_months_p1  time_diff_days_p2  time_diff_months_p2
0       2022             1           1         3          2           31           52                1               1             0              0                  0                 81             2.700000                 43             1.433333
1       2022             3           7         1         14           22            1               26               5             0              2                  1                -98            -3.266667               -137            -4.566667
2       2022             3           8        22          8            2           31               34               1             0              1                  0               -150            -5.000000               -188            -6.266667
3       2022             2           4        30         11           41           31               17               6             1              1                  0                -36            -1.200000                -75            -2.500000
4       2022             2           5         2         22            1           27               18               1             0              3                  1                -38            -1.266667                -77            -2.566667